### ISSUE TITLE
When run npm install --save vue-pdf-search-preivew，404 not found

### ISSUE THREAD

**Issue by liu-xinhui** [Youhandan/vue-pdf-search-viewer#1]
404 Not Found - GET https://registry.npmjs.com/vue-pdf-search-preivew - Not found

**Comment by Youhandan** [comment]
> 404 Not Found - GET https://registry.npmjs.com/vue-pdf-search-preivew - Not found

sorry, readme is error, project name is vue-pdf-search-viewer.
