### ISSUE TITLE
This dependency was not found

### ISSUE THREAD

**Issue by ScissorSeven** [Youhandan/vue-pdf-search-viewer#23]
I have installed it, but it runs with errors。
errors msg: 
This dependency was not found:

* vue-pdf-search-viewer in ./src/main.js

To install it, you can run: npm install --save vue-pdf-search-viewer

main.js
import PdfViewer from 'vue-pdf-search-viewer'
Vue.use(PdfViewer)

vue-cli Version is 4.0

**Comment by ScissorSeven** [comment]
I found that the "package.josn" file under the "vue-pdf-search-viewer" folder is missing the "main" configuration,so I added `"main": "lib/vue-pdf-search-viewer.common.js"`,then it runs successfully

**Comment by xeon-ye** [comment]
thx，solve my problem @ScissorSeven

**Comment by Youhandan** [comment]
> 

vue.config.js is configed？

**Comment by ScissorSeven** [comment]
"package.josn" is missing “main”

**Comment by Youhandan** [comment]
fix problem.
