### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_c')     at Proxy.render (vue-pdf-search-viewer.common.js:32254:83)

### ISSUE THREAD

**Issue by shravanikandadai** [Youhandan/vue-pdf-search-viewer#34]
Receiving this error while using pdf-viewer in my app

PS: Added "main": "lib/vue-pdf-search-viewer.common.js" to package.json

**Comment by Youhandan** [comment]
Already add it to lib-release branch，and publish to npm. This question is same as #23
